### ISSUE TITLE
Negative Coins

### ISSUE THREAD

**Issue by dcenygma** [MarcElAcoplao/CheckBackMod#3]
I clicked on "Unbox a Random Universal Pet for 250 coins" when I didn't have enough and it deducted 250 coins anyways, leaving me in the negative.

**Comment by MarcElAcoplao** [comment]
this was already fixed some time ago... when was the last time you refreshed?
[I opened a new incognito page right now and didn't get this bug anymore]

**Comment by dcenygma** [comment]
Looks like it has been fixed but unfortunately my negative balance has set me back a lot, is there any way to fix that?

**Comment by MarcElAcoplao** [comment]
You'll have to add yourself the coins or if you don't know how to change that, dm me on discord with your save and I can fix that

**Comment by dcenygma** [comment]
I just now modified my count in the console, since bug isn't around anymore I'm all good. Thanks!
